### ISSUE TITLE
Add execution time support

### ISSUE THREAD

**Issue by EFanZh** [johnterickson/cargo2junit#15]
Recently, Rust has merged a `--report-time` flag (rust-lang/rust#64663) into the test library so that the execution time is printed. I think maybe cargo2unit can support this feature.

**Comment by johnterickson** [comment]
@EFanZh Can you pull master and try it out? I'd love a second pair of eyes before I publish 😊

**Comment by EFanZh** [comment]
I have tried the latest cargo2junit with nightly Rust, the result looks good to me. But I’ll have to wait three months before I can use this feature with stable Rust.

**Comment by johnterickson** [comment]
Published - for those on nightly add you say 😁
