### ISSUE TITLE
Include timings

### ISSUE THREAD

**Issue by johnterickson** [johnterickson/cargo2junit#3]

**Comment by mathstuf** [comment]
It looks like cargo might need to provide this information first :/ .

**Comment by svenstaro** [comment]
Seems it includes it just fine in the JSON output:
```
{ "type": "suite", "event": "ok", "passed": 15, "failed": 0, "allowed_fail": 0, "ignored": 0, "measured": 0, "filtered_out": 0, "exec_time": 0.219172866 }
```

**Comment by mathstuf** [comment]
I was thinking about per-test timings, not test suite level timings.

**Comment by svenstaro** [comment]
Well, it would be a start though.

**Comment by svenstaro** [comment]
Actually, we can get the per-test timings just fine: `-Z unstable-options --format json --report-time`
```
{ "type": "suite", "event": "started", "test_count": 2 }
{ "type": "test", "event": "started", "name": "can_get_health" }
{ "type": "test", "event": "started", "name": "can_get_index" }
{ "type": "test", "name": "can_get_health", "event": "ok", "exec_time": 0.039503535 }
{ "type": "test", "name": "can_get_index", "event": "ok", "exec_time": 0.029446912 }
{ "type": "suite", "event": "ok", "passed": 2, "failed": 0, "allowed_fail": 0, "ignored": 0, "measured": 0, "filtered_out": 0, "exec_time": 0.044548753 }
```

**Comment by svenstaro** [comment]
Actually it seems to just work already in cargo2junit: `-Z unstable-options --format json --report-time | cargo2junit`. It's implemented [here](https://github.com/johnterickson/cargo2junit/blob/01041853b9e1dd47395a007f109733cdc635e960/src/main.rs#L72).

**Comment by mathstuf** [comment]
Oh nifty. That's good to hear. I guess this can be closed then?

**Comment by svenstaro** [comment]
I just confirmed that the timings show up alright in GitLab so yeah. @johnterickson can you close this?

**Comment by mathstuf** [comment]
I can verify that this is working in my GitLab-based project as well.

**Comment by johnterickson** [comment]
Glad to hear this is all working!
