### ISSUE TITLE
Missing tags?

### ISSUE THREAD

**Issue by orhun** [johnterickson/cargo2junit#75]
Hello!

I saw that there are a couple of commits that bump the version but there isn't any corresponding tags created. For example:

- https://github.com/johnterickson/cargo2junit/commit/6a80c509ecb67fa547480f916e5e386101be15e1 (`0.1.12`)
- https://github.com/johnterickson/cargo2junit/commit/f57a153e34022aface6134e236f5370f9e296f8c (`0.1.9`)

I was wondering if you are going to create and push tags so that the latest revision of the source code can be downloaded from GitHub?

**Comment by johnterickson** [comment]
Good call! Added.
