### ISSUE TITLE
Parse error on windows

### ISSUE THREAD

**Issue by Alxandr** [johnterickson/cargo2junit#8]
I got the following error on windows:

```
Error: Custom { kind: Other, error: StringError("Error parsing \'{ \"type\": \"test\", \"event\": \"started\", \"name\": \"src\\lib.rs -  (line 17)\" }\': invalid escape at line 1 column 52") }
```

This might be a serde/json error (seems like it), but it works on the other OSes, so I'm guessing it's OSString or newline related. Maybe it would be possible to normalize the input before JSON parsing it?

**Comment by johnterickson** [comment]
Could you capture the failing JSON? Maybe create a PR to add it to the tests folder? 😁

**Comment by Alxandr** [comment]
On a tablet right now, so manipulation json is a bit iffy. The build is here: https://dev.azure.com/yolo-dev/yolodev-github-projects/_build/results?buildId=49&view=logs&j=36eaf41f-1d10-545c-9fe3-8bc057ba96da

For now I just disabled using cargo2junit on windows, so master *should* still have the same problem. I don't have rust setup on any windows environments unfortunately.
